#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-PropertyListFilter
version:      0.02
version_from: PropertyListFilter.pm
installdirs:  site
requires:
    Mac::PropertyList:             0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
